### ISSUE TITLE
no separate packing function for sub message

### ISSUE THREAD

**Issue by usergoodvery** [protobuf-c/protobuf-c#366] opened 2019-03-23 08:54 UTC
Assuming I have the following schema:
message Outer {
    message Inner {
        optional uint32 id_inner  = 1;
    }
     optional uint32 id_outer  = 1;
 }

The compiler will create the type 'Outer__Inner' which is fine, but it doesn't generate a separate packing function for inner a la Outer__Inner_pack(...). Is that design feature?

**Comment by lipnitsk** [comment] 2019-05-17 18:11
Duplicate of #240

**Closed by lipnitsk** 2019-05-17 18:11 UTC
