### ISSUE TITLE
protobuf-c 1.4.x cygwin (win10pro) build fails 

### ISSUE THREAD

**Issue by timofey-retailnext** [protobuf-c/protobuf-c#518] opened 2022-07-23 01:40 UTC
applies to 1.4.0 and 1.4.1

cmd line:
 && ./configure \
                        CFLAGS=-std=c11 \
                        CXXFLAGS=-std=c++11 \
                        CPPFLAGS=-D_XOPEN_SOURCE=500 \
                        --prefix=/opt/XXX \
                && make \
                && ${SUDO} make install

build log: 

Extracting from protobuf-c-1.4.1.tar.gz ...
No patches
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3
checking whether ln -s works... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-cygwin
checking host system type... x86_64-pc-cygwin
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/x86_64-pc-cygwin/bin/ld.exe
checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 8192
checking how to convert x86_64-pc-cygwin file names to x86_64-pc-cygwin format... func_convert_file_noop
checking how to convert x86_64-pc-cygwin file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-cygwin/bin/ld.exe option to reload object files... -r
checking for file... file
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/x86_64-pc-cygwin/bin/ld.exe
checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
checking whether the g++ linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
checking for g++ option to produce PIC... -DDLL_EXPORT -DPIC
checking if g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether C compiler accepts "-Wc99-c11-compat"... yes
checking whether C compiler accepts "-Werror=incompatible-pointer-types"... yes
checking whether C compiler accepts "-Werror=int-conversion"... yes
checking whether C compiler accepts "-Wnull-dereference"... yes
checking for doxygen... doxygen
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether g++ supports C++11 features with -std=c++11... yes
checking for protobuf... yes
checking for google/protobuf/compiler/command_line_interface.h... yes
checking for protoc... /opt/XXX/bin/protoc
checking if LD -Wl,--version-script works... yes
checking whether self tests are run under valgrind... no
checking whether to build with code coverage support... no
checking whether byte ordering is bigendian... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating protobuf-c/libprotobuf-c.pc
config.status: creating Doxyfile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

    protobuf-c 1.4.1

        CC:                     gcc
        CFLAGS:                 -std=c11
        CXX:                    g++ -std=c++11
        CXXFLAGS:               -std=c++11
        LDFLAGS:
        LIBS:

        prefix:                 /opt/XXX
        sysconfdir:             ${prefix}/etc
        libdir:                 ${exec_prefix}/lib
        includedir:             ${prefix}/include
        pkgconfigdir:           ${libdir}/pkgconfig

        bigendian:              no
        protobuf version:       libprotoc 3.18.2

  GEN      protobuf-c/protobuf-c.pb.cc
  CXX      protoc-c/protoc_gen_c-c_bytes_field.o
  CXX      protoc-c/protoc_gen_c-c_enum.o
  CXX      protoc-c/protoc_gen_c-c_enum_field.o
  CXX      protoc-c/protoc_gen_c-c_extension.o
  CXX      protoc-c/protoc_gen_c-c_field.o
  CXX      protoc-c/protoc_gen_c-c_file.o
  CXX      protoc-c/protoc_gen_c-c_generator.o
  CXX      protoc-c/protoc_gen_c-c_helpers.o
  CXX      protoc-c/protoc_gen_c-c_message.o
  CXX      protoc-c/protoc_gen_c-c_message_field.o
  CXX      protoc-c/protoc_gen_c-c_primitive_field.o
  CXX      protoc-c/protoc_gen_c-c_service.o
  CXX      protoc-c/protoc_gen_c-c_string_field.o
  CXX      protobuf-c/protoc_c_protoc_gen_c-protobuf-c.pb.o
  CXX      protoc-c/protoc_gen_c-main.o
  CXXLD    protoc-c/protoc-gen-c.exe
  GEN      t/test.pb-c.c
[libprotobuf WARNING google/protobuf/compiler/parser.cc:649] No syntax specified for the proto file: t/test.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
  GEN      t/test-full.pb-c.c
[libprotobuf WARNING google/protobuf/compiler/parser.cc:649] No syntax specified for the proto file: t/test-full.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
  GEN      t/test-optimized.pb-c.c
[libprotobuf WARNING google/protobuf/compiler/parser.cc:649] No syntax specified for the proto file: t/test-optimized.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
  GEN      t/test-full.pb.cc
[libprotobuf WARNING google/protobuf/compiler/parser.cc:649] No syntax specified for the proto file: t/test-full.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
  CXX      t/generated-code2/cxx_generate_packed_data-cxx-generate-packed-data.o
  CXX      t/generated_code2_cxx_generate_packed_data-test-full.pb.o
  CXX      protobuf-c/t_generated_code2_cxx_generate_packed_data-protobuf-c.pb.o
  CXXLD    t/generated-code2/cxx-generate-packed-data.exe
  GEN      t/generated-code2/test-full-cxx-output.inc
/bin/sh: line 1: 31562 Segmentation fault      (core dumped) ./t/generated-code2/cxx-generate-packed-data.exe > ./t/generated-code2/test-full-cxx-output.inc
make: *** [Makefile:2730: t/generated-code2/test-full-cxx-output.inc] Error 139

**Comment by timofey-retailnext** [comment] 2022-07-23 01:42
$ gcc --version
gcc (GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ make --version
GNU Make 4.3
Built for x86_64-pc-cygwin
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by tbvdm** [comment] 2022-07-30 17:41
This looks like a duplicate of #483.

**Comment by timofey-retailnext** [comment] 2022-07-30 21:09
yes, #483 recommended to switch to c17/c++17  -> this helped.

**Comment by edmonds** [comment] 2023-11-26 00:09
This might be fixed in 1.5.0, please reopen if that's not the case.

**Closed by edmonds** 2023-11-26 00:09 UTC
